version: 0.2

phases:
  install:
    commands:
      - npm install
      - apt install nginx -y
  build:
    commands:
      - cp public/index.html /var/www/html
      - sudo systemctl restart nginx
      
      

artifacts:
  files:
    - '**/*'

